---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
  labels:
    "group": "hadoop"
    "app.kubernetes.io/component": "hdfs"
    "app.kubernetes.io/version": "2.7.7"
    "app.kubernetes.io/part-of": "hadoop"
spec:
  selector:
    app: hadoop-datanode
  ports:
    - name: "dn-port"
      port: 50010
    - name: "dn-ipc-port"
      port: 50020
    - name: "dn-http-port"
      port: 50075
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  labels:
    app: hadoop-datanode
    group: "hadoop"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hadoop-datanode
      group: "hadoop"
  template:
    metadata:
      labels:
        app: hadoop-datanode
        group: "hadoop"
    spec:    
      containers:
      - name: hadoop-datanode
        image: aiurtech/hadoop-datanode:0.8.3
        ports:
        - containerPort: 50010
        - containerPort: 50020
        - containerPort: 50075
        resources:
          requests:
            memory: "300Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "2000m"
      hostname: hadoop-datanode
      restartPolicy: Always
