---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  labels:
    "group": "hadoop"
    "app.kubernetes.io/component": "hdfs"
    "app.kubernetes.io/version": "2.7.7"
    "app.kubernetes.io/part-of": "hadoop"
spec:
  selector:
    app: hadoop-namenode
  ports:
    - name: "nn-port"
      port: 8020
    - name: "nn-http-port"
      port: 50070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
  labels:
    app: hadoop-namenode
    group: "hadoop"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hadoop-namenode
      group: "hadoop"
  template:
    metadata:
      labels:
        app: hadoop-namenode
        group: "hadoop"
    spec:    
      containers:
      - name: hadoop-namenode
        image: aiurtech/hadoop-namenode:0.8.2
        ports:
        - containerPort: 8020
        - containerPort: 50070
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      hostname: hadoop-namenode
      restartPolicy: Always
