apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
spec:
  selector:
    app: hadoop-namenode
  ports:
    - name: "nn-port"
      port: 8020
      targetPort: 8020
    - name: "nn-http-port"
      port: 50070
      targetPort: 50070