apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
spec:
  selector:
    app: hadoop-datanode
  ports:
    - name: "dn-port"
      port: 50010
      targetPort: 50010
    - name: "dn-ipc-port"
      port: 50020
      targetPort: 50075
    - name: "dn-http-port"
      port: 50075
      targetPort: 50075
