---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    "group": "hadoop"
    "app.kubernetes.io/component": "hive-metastore"
    "app.kubernetes.io/version": "1.2.1"
    "app.kubernetes.io/part-of": "hadoop"
spec:
  selector:
    app: hive-metastore
  ports:
    - name: "hive-ms-port"
      port: 9083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
    group: "hadoop"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hive-metastore
      group: "hadoop"
  template:
    metadata:
      labels:
        app: hive-metastore
        group: "hadoop"
    spec:    
      containers:
      - name: hive-metastore
        image: aiurtech/hive-metastore:0.8.3
        ports:
        - containerPort: 9083
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "600Mi"
            cpu: "1000m"
      hostname: hive-metastore
      restartPolicy: Always
