---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-postgresql
  labels:
    "group": "hadoop"
    "app.kubernetes.io/component": "postgres"
    "app.kubernetes.io/version": "11"
    "app.kubernetes.io/part-of": "hadoop"
spec:
  selector:
    app: hive-metastore-postgresql
  ports:
    - name: "pg-port"
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore-postgresql
  labels:
    app: hive-metastore-postgresql
    group: "hadoop"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hive-metastore-postgresql
      group: "hadoop"
  template:
    metadata:
      labels:
        app: hive-metastore-postgresql
        group: "hadoop"
    spec:    
      containers:
      - name: hive-metastore-postgresql
        image: aiurtech/hive-metastore-postgresql:0.8.2
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
      hostname: hive-metastore-postgresql
      restartPolicy: Always
