---
apiVersion: v1
kind: Service
metadata:
  name: hive
  labels:
    "group": "hadoop"
    "app.kubernetes.io/component": "hive"
    "app.kubernetes.io/version": "1.2.1"
    "app.kubernetes.io/part-of": "hadoop"
spec:
  selector:
    app: hive
  ports:
    - name: "hive-thrift-http-port"
      port: 10001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive
  labels:
    app: hive
    group: "hadoop"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hive
      group: "hadoop"
  template:
    metadata:
      labels:
        app: hive
        group: "hadoop"
    spec:    
      containers:
      - name: hive
        image: aiurtech/hive:0.8.2
        ports:
        - containerPort: 10001
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "600Mi"
            cpu: "1000m"
      hostname: hive
      restartPolicy: Always
